site_name: SADIF
site_description: Documentation about SADIF
site_author: CorrêaLabs
site_url: https://docs_sadif.florestleaks.com
copyright: © 2024 CorrêaLabs. All rights reserved
repo_name: GitHub
repo_url: https://github.com/florestleaks/SADIF/
edit_uri: https://github.com/florestleaks/SADIF/tree/main/docs
theme:
  name: material
  custom_dir: overrides
  features:
  - navigation.tabs
  - navigation.path
  - navigation.footer
  - navigation.expand
  - content.action.edit
  - content.action.view
  - content.code.annotate
  - content.code.copy
  - search.highlight
  palette:
    scheme: filigran
  font:
    text: IBM Plex Sans
    code: Roboto Mono
extra_css:
- assets/css/custom.css
markdown_extensions:
  toc:
    permalink: true
  markdown.extensions.codehilite:
    guess_lang: false
  mdx_include:
    base_path: docs
  admonition: null
  codehilite: null
  extra: null
  pymdownx.tabbed:
    alternate_style: true
  pymdownx.tilde: null
  attr_list: null
  md_in_html: null
  pymdownx.highlight:
    use_pygments: true
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: false
    auto_title: false
  pymdownx.tasklist:
    custom_checkbox: true
  pymdownx.snippets:
    url_download: true
extra:
  version:
    provider: mike
  generator: false
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/florestleaks/SADIF
  - icon: fontawesome/brands/slack
    link: https://discord.gg/UtDMf4wF4Q
  - icon: fontawesome/brands/linkedin
    link: https://www.linkedin.com/in/luizgustavocorrea/
plugins:
- mike:
    alias_type: symlink
    canonical_version: latest
- search
- git-committers:
    repository: florestleaks/SADIF
    branch: main
- git-revision-date-localized:
    enable_creation_date: true
    type: timeago
- glightbox
- privacy
- info:
    enabled: false
    enabled_on_serve: true
- search:
    pipeline:
    - stemmer
    - stopWordFilter
    - trimmer
- group:
    plugins:
    - optimize
    - minify
- blog:
    categories_url_format: category/{slug}
    authors: true
    authors_file: '{blog}/.authors.yml'
    pagination_url_format: page/{page}
- rss:
    match_path: blog/posts/.*
    date_from_meta:
      as_creation: date
    categories:
    - categories
    - tags
- mkdocstrings:
    handlers:
      python:
        paths:
        - src
        options:
          extensions:
          - griffe_typingdoc
          show_if_no_docstring: true
          show_source: true
          allow_inspection: false
          show_bases: true
          preload_modules:
          - sadif
          parameter_headings: true
          show_root_heading: false
          show_root_toc_entry: true
          show_root_full_path: true
          show_root_members_full_path: true
          show_object_full_path: true
          group_by_category: true
          show_category_heading: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          docstring_style: numpy
          show_docstring_attributes: true
          show_docstring_functions: true
          show_docstring_classes: true
          show_docstring_modules: true
          show_docstring_description: true
          show_docstring_other_parameters: true
          inherited_members: true
          members_order: source
          separate_signature: true
          unwrap_annotated: true
          filters:
          - '!^_'
          merge_init_into_class: true
          docstring_section_style: spacy
          signature_crossrefs: true
nav:
- Home: index.md
- SDK Setup:
  - Ubuntu: development/environment_ubuntu.md
- Development:
  - Prerequisites:
    - Ubuntu: development/environment_ubuntu.md
    - Windows: development/environment_windows.md
  - Platform: development/platform.md
  - Python library: development/python.md
  - Connectors: development/connectors.md
  - Playground: development/api-usage.md
- Reference (Code API):
  - clientmanager:
    - client_data_export:
      - Clientmanagerexport:
        - reference/sadif/clientmanager/client_data_export/ClientManagerExport.md
    - client_data_import:
      - Clientmanagerimport:
        - reference/sadif/clientmanager/client_data_import/ClientManagerImport.md
    - client_data_manager:
      - Clientmanager:
        - reference/sadif/clientmanager/client_data_manager/ClientManager.md
  - config:
    - sadif_config:
      - Sadifconfiguration:
        - reference/sadif/config/sadif_config/SadifConfiguration.md
  - frameworks_drivers:
    - crawler/base_crawler:
      - Basecrawler:
        - reference/sadif/frameworks_drivers/crawler/base_crawler/BaseCrawler.md
    - crawler/crawler_manager:
      - Crawlermanager:
        - reference/sadif/frameworks_drivers/crawler/crawler_manager/CrawlerManager.md
    - gitmanager:
      - Gitmanager:
        - reference/sadif/frameworks_drivers/gitmanager/GitManager.md
    - log_manager/sadif_log:
      - Logmanager:
        - reference/sadif/frameworks_drivers/log_manager/sadif_log/LogManager.md
    - modules_manager:
      - Moduledatabasemanager:
        - reference/sadif/frameworks_drivers/modules_manager/ModuleDatabaseManager.md
    - notification/webhook:
      - Webhooksender:
        - reference/sadif/frameworks_drivers/notification/webhook/WebhookSender.md
    - sadif_yara/yara_compiler:
      - Sadifyaracompiler:
        - reference/sadif/frameworks_drivers/sadif_yara/yara_compiler/SadifYaraCompiler.md
    - sadif_yara/yara_crud:
      - Yaracrud:
        - reference/sadif/frameworks_drivers/sadif_yara/yara_crud/YaraCrud.md
    - sadif_yara/yara_export:
      - Yararulesexporter:
        - reference/sadif/frameworks_drivers/sadif_yara/yara_export/YaraRulesExporter.md
    - sadif_yara/yara_import:
      - Yararulesimporter:
        - reference/sadif/frameworks_drivers/sadif_yara/yara_import/YaraRulesImporter.md
    - web/authenticator:
      - Authenticator:
        - reference/sadif/frameworks_drivers/web/authenticator/Authenticator.md
    - web/authenticator/basic_auth_strategy:
      - Basicauthstrategy:
        - reference/sadif/frameworks_drivers/web/authenticator/basic_auth_strategy/BasicAuthStrategy.md
    - web/authenticator/bearer_auth_strategy:
      - Bearerauthstrategy:
        - reference/sadif/frameworks_drivers/web/authenticator/bearer_auth_strategy/BearerAuthStrategy.md
    - web/authenticator/digest_auth_strategy:
      - Digestauthstrategy:
        - reference/sadif/frameworks_drivers/web/authenticator/digest_auth_strategy/DigestAuthStrategy.md
    - web/session_manager:
      - Sessionmanager:
        - reference/sadif/frameworks_drivers/web/session_manager/SessionManager.md
  - interfaces:
    - base_modules:
      - Ibasemodule:
        - reference/sadif/interfaces/base_modules/IBaseModule.md
    - web/authenticator:
      - Authstrategy:
        - reference/sadif/interfaces/web/authenticator/AuthStrategy.md
  - modules:
    - crawler/targeted_crawler/pastebin:
      - Pastebinplcrawler:
        - reference/sadif/modules/crawler/targeted_crawler/pastebin/PastebinPLCrawler.md
    - populate/url_to_dbs/ransomwhatimport:
      - Ransomwhatimport:
        - reference/sadif/modules/populate/url_to_dbs/ransomwhatimport/RansomwhatImport.md
  - utils:
    - generete_string/markdown_string_generator:
      - Markdownstringgenerator:
        - reference/sadif/utils/generete_string/markdown_string_generator/MarkdownStringGenerator.md
    - generete_string/random_string_generator:
      - Randomstringgenerator:
        - reference/sadif/utils/generete_string/random_string_generator/RandomStringGenerator.md
